### PR TITLE
Updated Kondo model + basic form with photo

### PR DESCRIPTION
**Pull request by spioupiou**
Updated Kondo model so that one picture is attached + basic form template for Kondo creation

### CODE REVIEW

**Comment by hiroya210** [comment]
I think we also need to attach photo to our user model? for profile avatar

**Comment by carlnoval** [comment]
+1 to what Hiro said, onegaishimasu @spioupiou.

**Comment by TofuSupreme** [comment]
Yes, I agree with Hiro as well.

**Comment by spioupiou** [comment]
I attached a photo to model User and gave the possibility for the user to add a photo when he signs up or edits his profile. Seems to be working!
Screen Shot 2022-01-26 at 11 25 58
Screen Shot 2022-01-26 at 11 38 40

**Pull request merged**
